### ISSUE TITLE
is @types/react required?

### ISSUE THREAD

**Issue by aladdin-add** [sindresorhus/auto-bind#16]
https://github.com/sindresorhus/auto-bind/blob/25790655e4ee5c3a00c0cebd5a97180fcfe806aa/package.json#L38

I'm not using react, but the `@types/react` is installed. …（⊙＿⊙；）…

**Comment by kevva** [comment]
It's used for the TypeScript definition. Ideally it'd be a peer dependency, but there are probably a lot of TypeScript consumers of this module that doesn't use React.
