### ISSUE TITLE
Webpack production bundling error

### ISSUE THREAD

**Issue by erikvinicius5** [sindresorhus/auto-bind#2]
Uglify doesn't support es6 syntax and we're not supposed to run babel on  `node_modules` so it returns the following error.

```
ERROR in bundle.js from UglifyJs
Unexpected token: operator (>) [bundle.js:20620,23]
```

It took me a while to actually open the bundle file and check the line, for I thought I was doing something wrong. Then I had to figure out which dependency this was from. Ok, this part wasn't so difficult. haha

```
module.exports = self => {
	for (const key of Object.getOwnPropertyNames(self.constructor.prototype)) {
		const val = self[key];

		if (key !== 'constructor' && typeof val === 'function') {
			self[key] = val.bind(self);
		}
	}
};
```

I would submit a PR changing the arrow function syntax, but I'm not sure `const` should also be changed.

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446
