### ISSUE TITLE
Babel can't transpile because "Module parse failed: Unexpected token (22:39)"

### ISSUE THREAD

**Issue by rsshilli** [sindresorhus/auto-bind#21]
Hello,

I'm a first time user of this project. I installed auto-bind, and added it to a single class to try it out. When I tried to compile it, webpack/babel spit out this error message:
```
ERROR in C:/projects/qbdvision/node_modules/auto-bind/react.js
Module parse failed: Unexpected token (22:39)
You may need an appropriate loader to handle this file type.
| ];
|
| module.exports = (self, {exclude = [], ...options} = {}) => {
|       options.exclude = [
|               ...exclude,
 @ C:/projects/qbdvision/build/main/clientjs/processExplorer/process_explorer_page.jsx 12:37-63
```

Any ideas for me? I'm actually confused about what you're trying to do. I think the last argument should be `{exclude, ...options} = {exclude: []}`, right? Or perhaps this is some new double default syntax that I'm not aware of.

I'm using:
* Webpack: 4.8.3
* @babel/core: 7.11.6
* @babel/preset-env: 7.11.5
* @babel/preset-react: 7.10.4

**Comment by rsshilli** [comment]
For future people, the answer is that you need to install:
```
npm install babel-plugin-transform-object-rest-spread --save-dev
```

And then include it in your .babelrc:
```
  ...
  "plugins": [
    "transform-object-rest-spread",
  ...
```

**Comment by rsshilli** [comment]
Neverind. This worked once, I swear. But on subsequent recompiles it did nothing. I have no idea why.

**Comment by sindresorhus** [comment]
This has nothing to do specifically with this package. Babel config support can be asked elsewhere.
