### ISSUE TITLE
ReferenceError: Property 'Reflect' doesn't exist

### ISSUE THREAD

**Issue by RodolfoGS** [sindresorhus/auto-bind#22]
Hi, I used this library on `react-native` for a long time, and works perfect. But now I'm trying to enable Hermes engine and I having this error.

I think that this happen because Hermes doesn't support Reflect.

The error is originated in this line:
https://github.com/sindresorhus/auto-bind/blob/1f3e975d842cbceaa40ed6abdf680e54a9a3ef43/index.js#L8

![Screenshot_20201102-100732](https://user-images.githubusercontent.com/870365/97890579-509c8e00-1cf3-11eb-9bb2-51a94e694440.png)

**Comment by sindresorhus** [comment]
It's up to you to polyfill anything needed. This package officially only supports modern browsers and Node.js.
