### ISSUE TITLE
error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by L1mindOfficial** [sindresorhus/auto-bind#28]
hi 
Hello, when I used Auto-Bind version 5.0.1 in TypeScript
Error: 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module
```
How can I fix it?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
