### ISSUE TITLE
autoBind function needs a filter method

### ISSUE THREAD

**Issue by jlyonsmith** [sindresorhus/auto-bind#3]
Thanks for creating this project.  I see that there has been at least one fork that added React specific filters when choosing which methods to bind.  I'd really like to make this a more general purpose mechanism.  For example, if you just wanted to bind all methods that started with the word `handle` which is the convention that I use for event handler methods in React apps. I propose:

1. Adding an optional filter method parameter that allows custom filtering of the bind
2. Adding a predefined filter function to exclude standard React methods.

Neither of these additions would affect current users in any way.  If I prepared a PR would you be interested in merging it?

**Comment by sindresorhus** [comment]
Sure, PR welcome :)

**Comment by jlyonsmith** [comment]
Sorry for the long response here.  I created a PR, but I felt it was a bit too much as I basically rewrote the library in ES6 with a different test tool.  So I create a new package, [auto-bind2](https://www.npmjs.com/package/auto-bind2) based on your excellent work.
