### ISSUE TITLE
ES2015 arrow function not transpiled

### ISSUE THREAD

**Issue by enoh-barbu** [sindresorhus/auto-bind#4]
I don't know if this is a babel issue or you should use functions instead of arrow functions because I get an error on old browsers that don't support the new syntax: `SyntaxError: Unexpected token '>'`

![preview](https://user-images.githubusercontent.com/24221572/30907108-81f426e0-a382-11e7-852e-b9cc82d38437.jpg)

as well `const` declarations

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
