### ISSUE TITLE
Does not work in a browser

### ISSUE THREAD

**Issue by adierkens** [sindresorhus/auto-bind#7]
The ES2015ify-ing it broke the ability to use it in a web environment that's not Chrome 😢

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
